# Generated by Django 4.2.5 on 2024-10-10 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.TextField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("video", "Video"),
                        ]
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                ("text_color", models.CharField(default="#000000", max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="news_images/")),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_url", models.URLField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TextStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("text_color", models.CharField(default="#000000", max_length=7)),
                (
                    "font_style",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("italic", "Italic"),
                            ("bold", "Bold"),
                            ("underline", "Underline"),
                        ],
                        default="normal",
                        max_length=50,
                    ),
                ),
                ("font_size", models.IntegerField(default=12)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_styles",
                        to="news.content",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="content",
            name="image",
            field=models.ManyToManyField(
                blank=True, related_name="content_images", to="news.image"
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="news",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="news.news",
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="video_url",
            field=models.ManyToManyField(
                blank=True, related_name="content_videos", to="news.video"
            ),
        ),
    ]
