# Generated by Django 4.2.5 on 2024-09-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommunityModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "object",
                    models.CharField(
                        choices=[
                            ("học viên", "Học Viên"),
                            ("giảng viên", "Giảng Viên"),
                        ],
                        max_length=10,
                    ),
                ),
                ("password", models.CharField(max_length=16)),
                ("confirm_password", models.CharField(max_length=16)),
            ],
        ),
    ]
