# Generated by Django 4.2.5 on 2024-09-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tranning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=255)),
                ("course_code", models.CharField(max_length=100)),
                ("course_duration", models.CharField(max_length=100)),
                ("schedule", models.DateField()),
                ("tuition_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("target_audience", models.CharField(max_length=255)),
                ("link", models.CharField(max_length=255)),
                ("image_tranning", models.ImageField(upload_to="training_images/")),
                ("full_name", models.CharField(max_length=255)),
                ("major", models.CharField(max_length=255)),
                ("image_lecturer", models.ImageField(upload_to="lecturer_images/")),
                ("course_description", models.TextField()),
                ("detailed_description", models.TextField()),
            ],
        ),
    ]
