# Generated by Django 4.2.5 on 2024-10-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tranning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tranning",
            name="course_code",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
